# Generated by Django 3.1.7 on 2021-02-26 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretuber',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 25, 20, 39, 11, 112099)),
        ),
    ]
